name : "Deploy Busynes Infrastructure"
permissions:
    id-token: write
    contents: read
on:
    push: 
        branches: ['main']
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::160835721559:role/busynes-github-actions-role
                aws-region: eu-west-2
                audience: sts.amazonaws.com
            - name: Setup Python
              uses: actions/setup-python@v4
              with: 
                python-version: "3.12"
            - name: Installing Stripe Dependencies
              run: pip install stripe -t ./Backend
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
            - name: Terraform Init
              run: terraform init
              working-directory: ./Infra
            - name: Terraform Validate
              run: terraform validate
              working-directory: ./Infra
            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: ./Infra
              env:
                TF_VAR_stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
                TF_VAR_stripe_webhook_secret: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
